---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 8080, protocol: "tcp"}]
    - ["forwarded_port", {guest: 8080, host: 8081, protocol: "tcp"}]
    - ["forwarded_port", {guest: 443, host: 8443, protocol: "tcp"}]

# The forwarded_port port feature lets you connect to ports on the VM guest via
# localhost on the host. (Port 80/tcp: http traffic; port 443/tcp: https).
# see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[prestashop::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
