
default['prestashop']['ps_country'] = 'en'
default['prestashop']['ps_email'] = 'johndoe@prestashop.com'
default['prestashop']['ps_firstname'] = 'John'
default['prestashop']['ps_language'] = 'en'
default['prestashop']['ps_lastname'] = 'Doe'
default['prestashop']['ps_name'] = 'PrestaShop'
default['prestashop']['ps_password'] = '0123456789'
default['prestashop']['ps_rootdir'] = 'prestashop'
default['prestashop']['ps_version'] = '1.7.6.1'

default['prestashop']['psdb_name'] = 'prestashop'
default['prestashop']['psdb_user'] = 'ps_user'
default['prestashop']['psdb_password'] = 'ps_user'
default['prestashop']['psdb_prefix'] = 'ps_'
default['prestashop']['psdb_server'] = '127.0.0.1'
